[package]
name = "fontfor"
version = "0.4.0"
authors = ["7sDream <i@7sdre.am>"]
edition = "2021"
description = "find fonts which can show a specified character and preview them in terminal or browser"
homepage = "https://github.com/7sDream/fontfor"
repository = "https://github.com/7sDream/fontfor"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["font", "character", "cli", "utilities"]
categories = ["command-line-utilities", "text-processing", "visualization"]

[dependencies]
once_cell = "1"
httparse = "1"
crossterm = "0.27"
fontdb = "0.16"
ab_glyph = "0.2"
owned_ttf_parser = "0.20.0"
thiserror = "1.0.50"

[dependencies.clap]
version = "4"
features = ["derive", "unicode", "wrap_help"]

[dependencies.tui]
package = "ratatui"
version = "0.24"
default-features = false
features = ["crossterm"]
