[package]
name = "fontfor"
version = "0.3.1"
authors = ["7sDream <i@7sdre.am>"]
edition = "2018"
description = "find fonts which can show a specified character and preview them in terminal or browser"
homepage = "https://github.com/7sDream/fontfor"
repository = "https://github.com/7sDream/fontfor"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["font", "character", "cli", "utilities"]
categories = ["command-line-utilities", "text-processing", "visualization"]

[dependencies]
structopt = "0.3"
once_cell = "1"
httparse = "1"
freetype = "0.7"
crossterm = "0.17"

[target.'cfg(target_os = "linux")'.dependencies]
servo-fontconfig = "0.5"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9"
core-text = "19"

[dependencies.tui]
version = "0.10"
default-features = false
features = ["crossterm"]

# TODO: Delete me if servo-fontconfig-sys's new version will use static lib built by dep -sys crates
[patch.crates-io]
servo-fontconfig-sys = { git = "https://github.com/7sDream/libfontconfig", branch = "build/use-dep-built-static-lib-when-possible" }
