[package]
name = "fontfor"
version = "0.2.0"
authors = ["7sDream <i@7sdre.am>"]
edition = "2018"
description = "find fonts which can show a specified character and preview them in terminal or browser"
homepage = "https://github.com/7sDream/fontfor"
repository = "https://github.com/7sDream/fontfor"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["font", "character", "cli", "utilities"]
categories = ["command-line-utilities", "text-processing", "visualization"]

[dependencies]
structopt = "0.3.9"
servo-fontconfig = "0.4.0"
once_cell = "1.3.1"
httparse = "1.3.4"
freetype = "0.4.1"
crossterm = "0.14.2"

[dependencies.tui]
version = "0.8.0"
default-features = false
features = ["crossterm"]
