[package]
name = "fontfor"
version = "0.3.1"
authors = ["7sDream <i@7sdre.am>"]
edition = "2018"
description = "find fonts which can show a specified character and preview them in terminal or browser"
homepage = "https://github.com/7sDream/fontfor"
repository = "https://github.com/7sDream/fontfor"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["font", "character", "cli", "utilities"]
categories = ["command-line-utilities", "text-processing", "visualization"]

[dependencies]
structopt = "0.3"
once_cell = "1.3"
httparse = "1.3"
# freetype crate needs a patch https://github.com/servo/rust-freetype/pull/60
# due to the latest published version do not link to C library
# TODO: use prod version after freetype 0.5.3 or above is published
freetype = { git = "https://github.com/servo/rust-freetype", rev = "44aaca76a02ac6913ec75a10c7fcdbe6733d0428" }
crossterm = "0.17"

[target.'cfg(target_os = "linux")'.dependencies]
servo-fontconfig = "0.5"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.7"
core-text = "15.0"

[dependencies.tui]
version = "0.9"
default-features = false
features = ["crossterm"]
