[package]
name = "fontfor"
version = "0.1.1"
authors = ["7sDream <i@7sdre.am>"]
edition = "2018"
description = "find fonts which can show a specified character and preview them in browser"
homepage = "https://github.com/7sDream/fontfor"
repository = "https://github.com/7sDream/fontfor"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["font", "character", "cli", "utilities"]
categories = ["command-line-utilities", "text-processing", "visualization"]

[dependencies]
structopt = "0.3.7"
servo-fontconfig = "0.4.0"
once_cell = "1.2.0"
hyper = "0.13.1"

[dependencies.tokio]
version = "0.2.6"
features = ["rt-core", "blocking"]
