[package]
name = "fontfor"
version = "0.1.0"
authors = ["7sDream <i@7sdre.am>"]
edition = "2018"
description = "find fonts which can show a specified character"
repository = "https://github.com/7sDream/fontfor-rs"
readme = "README.md"
license-file = "COPYING"
keywords = ["font", "character", "cli", "command line", "tools"]
categories = ["command-line-utilities", "text-processing", "visualization"]
publish = false

[dependencies]
font-kit = "0.5.0"
