name: Action DepVer

on:
  workflow_dispatch:
  workflow_call:

jobs:
  depver:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
          rustup show
      - name: Install cargo-outdated
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-outdated
      - name: Check deps crates version
        run: |
          cargo outdated -R --exit-code 1 --verbose
