name: Action Lint

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      channel:
        type: string
        default: stable

jobs:
  lint:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: |
          rustup set auto-self-update disable
          rustup toolchain install ${{ inputs.channel }} --profile minimal -c clippy
          rustup toolchain install nightly --profile minimal -c rustfmt
          rustup show
      - name: Check code style
        run: |
          cargo +nightly fmt --all -- --check
      - name: Lint code by clippy(stable)
        uses: clechasseur/rs-clippy-check@v4
        with:
          toolchain: ${{ inputs.channel }}
          args: --all-targets --all-features -- -D warnings
