name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.draft && !github.event.release.prerelease }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ github.event.release.tag_name }}
      - name: Install Rust toolchains
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo registry and index
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Publish crate
        uses: actions-rs/cargo@v1
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.crates_io_token }}
        with:
          command: publish
          args: --registry crates-io --all-features --verbose
